const ADD_TO_CART="ADD_TO_CART";
const REMOVE_TO_CART="REMOVE_TO_CART";
const DECREASE_QUANTITY="DECREASE_QUANTITY";
const INCREASE_QUANTITY="INCREASE_QUANTITY";

export {ADD_TO_CART,REMOVE_TO_CART,DECREASE_QUANTITY,INCREASE_QUANTITY};